import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FileDataProvider } from "../components/providers/FileData";
import "./globals.css";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FileDataProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </FileDataProvider>
  );
}
